services:
  # Service 1: The main bot (Web Service)
  - type: web
    name: file-store-bot
    env: python
    buildCommand: ./build.sh
    startCommand: PATH=$PATH:$(pwd)/bin python3 main.py
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8011
      - key: PYTHON_VERSION
        value: 3.10.0
    plan: free

    plan: free
